config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :clientes
  resources :quartos
  resources :funcionarios
  resources :reservas

  scope :reservas do
    post '/disponibilidade' => 'reservas#disponibilidade', as: :disponibilidade
  end

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  get '/relatorios/dashboard' => 'relatorios#dashboard', as: :dashboard
end

app/models/cliente.rb
# == Schema Information
#
# Table name: clientes
#
#  idcliente       :integer          not null, primary key
#  nome            :string(255)      not null
#  email           :string(255)      not null
#  rg              :string(255)      not null
#  cpf             :string(255)      not null
#  telefone        :string(255)
#  celular         :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  data_nascimento :date
#

class Cliente < ActiveRecord::Base
  include ApplicationRecord

  # Campos de busca
  SEARCH_FIELDS = [
    :nome,
    :email
  ]

  # Valida a obrigatoriedade do nome.
  validates :nome, presence: true

  # Valida a obrigatoriedade e o formato do CPF.
  validates :cpf, cpf: true

  # Valida a unicidade do e-mail e do CPF.
  validates :email, :cpf, uniqueness: true

  # Antes da validação, formata alguns valores padrão.
  before_validation :set_default_values

  # Impede a remoção de clientes.
  before_destroy :validate_destroy

  # Adiciona um erro e não permite a remoção do cliente.
  def validate_destroy
    errors.add(:base, 'Clientes não podem ser removidos.')
    return false
  end

  # Remove a pontuação do CPF antes de validá-lo.
  def set_default_values
    self.cpf = self.cpf.gsub(/[^0-9]/, '') if self.cpf.present?
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # Títulos utilizados nas telas.
  TITLES = {
    index: 'Listagem de clientes',
    create: 'Novo cliente',
    show: 'Visualizar cliente',
    update: 'Editar cliente',
    destroy: 'Remover cliente'
  }

  # Definindo qual é a model usada pela controller.
  def model_klass
    Cliente
  end

  # Aplicando a ordenação.
  def apply_sorters
    @items = @items.order(:nome)
  end

  # Permite somente parâmetros através de uma "white list".
  def model_params
    params.require(:cliente).permit(:nome, :email, :rg, :cpf, :telefone, :celular, :data_nascimento)
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= bootstrap_form_for(@item, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-9') do |f| %>
  <%= f.text_field :nome, control_col: 'col-sm-4' %>
  <%= f.email_field :email, control_col: 'col-sm-4' %>
  <%= f.text_field :rg, control_col: 'col-sm-2' %>
  <%= f.text_field :cpf, control_col: 'col-sm-2' %>

  <%= f.text_field :data_nascimento, control_col: 'col-sm-3' %>

  <%= f.text_field :telefone, control_col: 'col-sm-2' %>
  <%= f.text_field :celular, control_col: 'col-sm-2' %>

  <hr />

  <%= f.form_group do %>
    <%= f.primary 'Salvar' %>

    <%= link_to 'Voltar', clientes_path, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function () { 
        $("#cliente_cpf").mask('999.999.999-99');
        $("#cliente_telefone, #cliente_celular").mask('(99) 99999-9999');
        $("#cliente_data_nascimento").mask('00/00/0000');
    });
  </script>
<% end %>

app/views/clientes/edit.html.erb
<h3><%= @title %></h3>

<%= render 'form' %>

app/views/clientes/index.html.erb
<div class="row page-title">
  <div class="col-xs-8">
    <h2><%= @title %></h2>
  </div>
  <div class="col-xs-4">
    <%= link_to @all_titles[:create], new_cliente_path, class: 'btn btn-primary pull-right' %>
  </div>
</div>

<h3><%= @url %></h3>

<%= bootstrap_form_tag(url: clientes_path, layout: :horizontal, method: :get, html: { class: 'form-search' }) do |f| %>
  <div class="row">
    <label class="col-sm-2 control-label" for="search"><%= I18n.t('general.search') %></label>
    <div class="col-sm-8">
      <%= search_field_tag :search, params[:search], class: 'form-control', hide_label: true, placeholder: I18n.t('general.search_tip', fields: Cliente.humanize_search_fields.to_sentence.downcase) %>
    </div>
    <div class="col-sm-2">
      <%= f.submit I18n.t('general.search'), class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>E-mail</th>
      <th class="text-center action-column">Ações</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td colspan="4"><%= page_entries_info @items %></td>
    </tr>
  </tfoot>
  <% if @items.present? %>
    <tbody>
      <% @items.each do |cliente| %>
        <tr>
          <td><%= cliente.nome %></td>
          <td><%= mail_to cliente.email %></td>
          <td class="text-center">
            <!-- Single button -->
            <div class="btn-group">
              <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
              </button>
              <ul class="dropdown-menu pull-right">
                <li><a href="<%= cliente_path(cliente) %>"><span class="glyphicon glyphicon-eye-open"></span> Ver</a></li>
                <li><a href="<%= edit_cliente_path(cliente) %>"><span class="glyphicon glyphicon-edit"></span> Editar</a></li>
                <li role="separator" class="divider"></li>
                <li class="text-danger">
                  <%= bootstrap_form_for(cliente, method: :delete) do end; %>
                  <a class="btn-delete-cliente" data-toggle="model" data-target="#modal-cliente" data-nome="<%= cliente.nome %>" href="#edit_cliente_<%= cliente.id %>">
                    <span class="glyphicon glyphicon-trash"></span> Remover
                  </a>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

<%= paginate(@items) if @items.present? %>

<div class="modal fade" tabindex="-1" role="dialog" id="modal-cliente">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body">
        Tem certeza que deseja excluir o cliente <b class="cliente-nome">nome do cliente</b>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-danger" data-form="" id="btn-confirm-remove">Remover</button>
      </div>
    </div>
  </div>
</div>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function() {
      $('#modal-cliente #btn-confirm-remove').click(function() {
        var formId = $(this).data('form');

        if (formId) {
          $(formId).submit();
        }
      });

      $('.btn-delete-cliente').click(function() {
        var formId = $(this).attr('href'),
          clienteNome = $(this).data('nome');

        $('#modal-cliente .cliente-nome').html(clienteNome);
        $('#modal-cliente #btn-confirm-remove').data('form', formId);

        $('#modal-cliente').modal();
      });
    });
  </script>
<% end %>

app/views/clientes/new.html.erb
<h3><%= @title %></h3>

<%= render 'form' %>

app/views/clientes/show.html.erb
<h3><%= @title %></h3>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @item.nome %></dd>

  <dt>E-mail:</dt>
  <dd><%= @item.email %></dd>

  <dt>RG:</dt>
  <dd><%= @item.rg %></dd>

  <dt>CPF:</dt>
  <dd><%= Util.mask_cpf @item.cpf %></dd>

  <dt>Data de aniversário:</dt>
  <dd><%= l @item.data_nascimento %></dd>

  <dt>Telefone:</dt>
  <dd><%= @item.telefone %></dd>

  <dt>Celular:</dt>
  <dd><%= @item.celular %></dd>
</dl>

<%= bootstrap_form_for(@item, method: :delete) do |f| %>
  <%= link_to 'Voltar', clientes_path, class: 'btn btn-primary' %>
  <%= link_to 'Editar', edit_cliente_path(@item), class: 'btn btn-primary' %>

  <%= f.submit 'Remover', class: 'btn btn-danger' %>
<% end %>