config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :clientes
  resources :quartos
  resources :funcionarios
  resources :reservas

  scope :reservas do
    post '/disponibilidade' => 'reservas#disponibilidade', as: :disponibilidade
  end

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  get '/relatorios/dashboard' => 'relatorios#dashboard', as: :dashboard
end

app/models/reserva.rb
# == Schema Information
#
# Table name: reservas
#
#  idreserva     :integer          not null, primary key
#  idfuncionario :integer          not null
#  idquarto      :integer          not null
#  idcliente     :integer          not null
#  data_entrada  :date             not null
#  data_saida    :date             not null
#  cafe_manha    :boolean          not null
#  almoco        :boolean          not null
#  jantar        :boolean          not null
#  valor_total   :float(24)        not null
#  observacoes   :text(65535)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Reserva < ActiveRecord::Base
  include ApplicationRecord

  # Campos de busca
  SEARCH_FIELDS = [
    :idfuncionario,
    :idquarto,
    :idcliente
  ]

  # Soft delete: indica para que o registro não seja excluído físicamente
  # do banco de dados, apenas salva a data da remoção e automaticamente
  # não retorna os itens já removidos do sistema
  acts_as_paranoid

  # Define a associação entre reserva e funcionário.
  belongs_to :funcionario, -> { with_deleted }, foreign_key: :idfuncionario

  # Define a associação entre reserva e quarto.
  belongs_to :quarto, foreign_key: :idquarto

  # Define a associação entre reserva e cliente.
  belongs_to :cliente, foreign_key: :idcliente

  # Valida a obrigatoriedade do funcionário, do quarto e do cliente.
  validates :funcionario, :quarto, :cliente, presence: true

  # Valida a obrigatoriedade da data de entrada, da data de saída e do valor total.
  validates :data_entrada, :data_saida, :valor_total, presence: true

  # Valida se os dados das refeições foram inseridos corretamente.
  validates :cafe_manha, :almoco, :jantar, inclusion: [true, false]

  # Executa uma validação personalizada.
  validate :valida_data_reserva

  # Antes da validação, define alguns valores para o registro.
  before_validation :set_default_values

  # Formata o número da reserva para o padrão "00001"
  def numero_reserva
    idreserva.to_s.rjust(5, '0') if idreserva?
  end

  # Preenche automaticamente o valor total baseado no valor da diária
  def set_default_values
    return true unless self.quarto.present? && self.data_entrada.present? && self.data_saida.present? && self.data_entrada < self.data_saida

    total_dias = (self.data_saida - self.data_entrada).to_i

    self.valor_total = total_dias * self.quarto.valor_diaria.to_f
  end

  # Valida se a data de entrada é menor que a data de saída.
  def valida_entrada_saida
    unless self.data_entrada < self.data_saida
      errors.add(:data_entrada, 'A data de entrada precisa ser menor do que a de saída.')
      return false
    end
  end

  # Valida se a data de saída é maior que a data de entrada.
  def valida_data_reserva
    return true unless self.quarto.present? && self.data_entrada? && self.data_saida?

    reserva = Reserva.where(idquarto: self.idquarto).where("data_entrada < ? AND data_saida > ?", data_saida, data_entrada).where.not(idreserva: self.idreserva).first

    if reserva.present?
      errors.add(:base, "Já existe uma reserva para o quarto #{reserva.quarto.numero} na data #{reserva.data_entrada.strftime('%d/%m/%Y')} à #{reserva.data_saida.strftime('%d/%m/%Y')}.")
      return false
    end
  end

  # Monta um conjunto com as refeições definidas na reserva.
  def refeicoes
    arr = []

    arr << 'Café da manhã' if self.cafe_manha?
    arr << 'Almoço' if self.almoco?
    arr << 'Jantar' if self.jantar?

    arr
  end

  # Recupera as informações das reservas e as formata para o padrão da
  # estrutura do dashboard.
  def self.dashboard_info data_inicial, data_final, only_occupied = nil
    info = {}

    reservas = Reserva.where("data_entrada < ? AND data_saida > ?", data_final, data_inicial)

    if only_occupied.present?
      reservas = reservas.limit(only_occupied)
    end

    reservas.each do |reserva|
      info[reserva.idquarto] ||= []

      (reserva.data_entrada..(reserva.data_saida - 1.day)).each do |tmp_data|
        info[reserva.idquarto].push tmp_data
      end
    end

    info
  end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:disponibilidade]

  # Títulos utilizados nas telas.
  TITLES = {
    index: 'Listagem de reservas',
    create: 'Nova reserva',
    show: 'Visualizar reserva',
    update: 'Editar reserva',
    destroy: 'Remover reserva'
  }

  # Definindo qual é a model usada pela controller.
  def model_klass
    Reserva
  end

  # Permite somente parâmetros através de uma "white list".
  def model_params
    params.require(:reserva).permit(:idfuncionario, :idquarto, :idcliente, :data_entrada, :data_saida, :cafe_manha, :almoco, :jantar, :observacoes)
  end

  def disponibilidade
    id = params[:id].to_i
    data_entrada = Date.parse(params[:data_entrada])
    data_saida = Date.parse(params[:data_saida])

    query = Reserva.select(:idquarto).where("data_entrada < ? AND data_saida > ?", data_saida, data_entrada)

    unless id.zero?
      query = query.where.not(idreserva: id)
    end

    quartos = Quarto.where("idquarto NOT IN(#{query.to_sql})")

    dias_reserva = (data_saida - data_entrada).to_i

    result = quartos.collect do |quarto|
      {
        idquarto: quarto.idquarto,
        numero: quarto.numero,
        valor_reserva: quarto.valor_diaria.to_f * dias_reserva
      }
    end

    render json: { data: result, meta: { success: true } }
  end
end

app/views/reservas/_form.html.erb
<%= bootstrap_form_for(@item, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-9') do |f| %>

    <%= f.alert_message "Por favor, corrija os problemas abaixo." %>
    
    <%= f.text_field :data_entrada, control_col: 'col-sm-3', value: @item.present? && @item.data_entrada? ? @item.data_entrada.strftime('%d/%m/%Y') : nil %>
    <%= f.text_field :data_saida, control_col: 'col-sm-3', value: @item.present? && @item.data_saida? ? @item.data_saida.strftime('%d/%m/%Y') : nil %>

    <% quartos = @item.persisted? ? [@item.quarto] : [] %>
    
    <%= f.select :idquarto, quartos.collect {|q| [ q.numero, q.idquarto ] }, { include_blank: true, control_col: 'col-sm-2' } %>

    <div class="form-group">
        <label class="col-sm-3 control-label">Valor <%= @item.valor_total.to_f.round(2) %></label>
        <div class="col-sm-3">
            <div class="input-group">
                <span class="input-group-addon">R$</span>
                <input class="form-control" id="reserva_valor_total_static" alt="decimal" type="text" readonly value="<%= @item.valor_total.to_f %>" />
            </div>
        </div>
    </div>

    <hr />

    <%= f.select :idcliente, Cliente.order(:nome).collect {|c| [ c.nome, c.idcliente ] }, { include_blank: true, control_col: 'col-sm-4' } %>
    <%= f.select :idfuncionario, Funcionario.order(:nome).collect {|f| [ f.nome, f.idfuncionario ] }, { include_blank: true, control_col: 'col-sm-4' } %>

    <hr />
    
    <%= f.form_group :meals do %>
        <%= f.label 'Refeições' %>
        <%= f.check_box :cafe_manha %>
        <%= f.check_box :almoco %>
        <%= f.check_box :jantar %>
    <% end %>

    <hr />

    <%= f.form_group do %>
        <%= f.primary 'Salvar' %>

        <%= link_to 'Voltar', quartos_path, class: 'btn btn-primary' %>
    <% end %>
<% end %>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function () {
        var idReserva = <%= @item.idreserva? || 'null' %>,
            ultimaDataEntrada,
            ultimaDataSaida;

        function bloqueiaComboQuarto() {
            $('#reserva_idquarto').attr('disabled', '');
        }
        function limparComboQuarto() {
            $('#reserva_idquarto option').remove();
            bloqueiaComboQuarto();
        }

        $("#reserva_data_entrada, #reserva_data_saida").mask('00/00/0000');

        if (!idReserva) {
            limparComboQuarto();
        }
        
        $('#reserva_idquarto').change(function() {
            var idQuarto = $(this).val(),
                option = $(this).find('[value=' + idQuarto + ']');

            if (option) {
                var valorReserva = $(option).data('valor_reserva');

                $('#reserva_valor_total_static').val(valorReserva);
            }
        });

        $('#reserva_data_entrada, #reserva_data_saida').blur(function() {
            var dataEntrada = $('#reserva_data_entrada').val(),
                dataSaida = $('#reserva_data_saida').val();

            if (dataEntrada && dataSaida) {
                var url = '<%= disponibilidade_url %>',
                    idQuarto = $('#reserva_idquarto').val(),
                    data = {
                        id: idReserva,
                        data_entrada: dataEntrada,
                        data_saida: dataSaida
                    };

                limparComboQuarto();

                $.post(url, data, function(response, textSuccess) {
                    console.log('SUCCESS', 'RESPONSE', response);

                    if (response.meta.success) {
                        if (response.data.length > 0) {
                            $('#reserva_idquarto').removeAttr('disabled');
                            $('#reserva_idquarto option').remove();

                            var option = $('<option/>');
                            option.attr({
                                value: '',
                                'data-valor_reserva': 0
                            })
                            option.text('Selecione...');
                            $('#reserva_idquarto').append(option);
                            
                            for (i in response.data) {
                                var option = $('<option/>');

                                option.attr({
                                    value: response.data[i].idquarto,
                                    'data-valor_reserva': response.data[i].valor_reserva
                                });
                                option.text(response.data[i].numero);

                                $('#reserva_idquarto').append(option);
                            }

                            if (idQuarto) {
                                $('#reserva_idquarto').val(idQuarto);
                            }
                        }
                    }
                });
            } else {
                limparComboQuarto();
            }
        });
    });
  </script>
<% end %>

app/views/reservas/edit.html.erb
<h3><%= @title %></h3>

<%= render 'form' %>

app/views/reservas/index.html.erb
<div class="row page-title">
  <div class="col-xs-8">
    <h2><%= @title %></h2>
  </div>
  <div class="col-xs-4">
    <%= link_to @all_titles[:create], new_reserva_path, class: 'btn btn-primary pull-right' %>
  </div>
</div>

<h3><%= @url %></h3>

<%= bootstrap_form_tag(url: reservas_path, layout: :horizontal, method: :get, html: { class: 'form-search' }) do |f| %>
  <div class="row">
    <label class="col-sm-2 control-label" for="search"><%= I18n.t('general.search') %></label>
    <div class="col-sm-8">
      <%= search_field_tag :search, params[:search], class: 'form-control', hide_label: true, placeholder: I18n.t('general.search_tip', fields: Reserva.humanize_search_fields.to_sentence.downcase) %>
    </div>
    <div class="col-sm-2">
      <%= f.submit I18n.t('general.search'), class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th data-toggle="tooltip" title="Número da reserva">#</th>
      <th>Cliente</th>
      <th>Quarto</th>
      <th>Funcionário</th>
      <th>Checkin</th>
      <th>Checkout</th>
      <th>Valor total</th>
      <th class="text-center action-column">Ações</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td colspan="8"><%= page_entries_info @items %></td>
    </tr>
  </tfoot>
  <% if @items.present? %>
    <tbody>
      <% @items.each do |reserva| %>
        <tr>
          <td><%= reserva.numero_reserva %></td>
          <td><%= reserva.cliente.nome %></td>
          <td><%= reserva.quarto.numero %></td>
          <td><%= reserva.funcionario.nome %></td>
          <td><%= l reserva.data_entrada %></td>
          <td><%= l reserva.data_saida %></td>
          <td><%= number_to_currency(reserva.valor_total) %></td>
          <td class="text-center">
            <!-- Single button -->
            <div class="btn-group">
              <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
              </button>
              <ul class="dropdown-menu pull-right">
                <li><a href="<%= reserva_path(reserva) %>"><span class="glyphicon glyphicon-eye-open"></span> Ver</a></li>
                <li><a href="<%= edit_reserva_path(reserva) %>"><span class="glyphicon glyphicon-edit"></span> Editar</a></li>
                <li role="separator" class="divider"></li>
                <li class="text-danger">
                  <%= bootstrap_form_for(reserva, method: :delete) do end; %>
                  <a class="btn-delete-reserva" data-toggle="model" data-target="#modal-reserva" data-nome="<%= reserva.numero_reserva %>" href="#edit_reserva_<%= reserva.id %>">
                    <span class="glyphicon glyphicon-trash"></span> Remover
                  </a>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

<%= paginate(@items) if @items.present? %>

<div class="modal fade" tabindex="-1" role="dialog" id="modal-reserva">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body">
        Tem certeza que deseja excluir a reserva <b class="reserva-nome">nome do reserva</b>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-danger" data-form="" id="btn-confirm-remove">Remover</button>
      </div>
    </div>
  </div>
</div>
<% content_for :javascripts do %>
  <script>
    $(document).ready(function() {
      $('#modal-reserva #btn-confirm-remove').click(function() {
        var formId = $(this).data('form');

        if (formId) {
          $(formId).submit();
        }
      });

      $('.btn-delete-reserva').click(function() {
        var formId = $(this).attr('href'),
          reservaNome = $(this).data('nome');

        $('#modal-reserva .reserva-nome').html(reservaNome);
        $('#modal-reserva #btn-confirm-remove').data('form', formId);

        $('#modal-reserva').modal();
      });
      
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      });
    });
  </script>
<% end %>

app/views/reservas/new.html.erb
<h3><%= @title %></h3>

<%= render 'form' %>

app/views/reservas/show.html.erb
<h3><%= @title %></h3>

<dl class="dl-horizontal">
  <dt>Número da reserva:</dt>
  <dd><%= @item.idreserva.to_s.rjust(5, '0') %></dd>

  <dt>Valor total:</dt>
  <dd><%= number_to_currency(@item.valor_total) %></dd>

  <dt>Cliente:</dt>
  <dd><%= @item.cliente.nome %></dd>

  <dt>Quarto:</dt>
  <dd><%= @item.quarto.numero %></dd>

  <dt>Funcionário:</dt>
  <dd><%= @item.funcionario.nome %></dd>

  <dt>Refeições:</dt>
  <dd><%= @item.refeicoes.to_sentence.capitalize %></dd>

  <dt>Entrada:</dt>
  <dd><%= @item.data_entrada.strftime('%d/%m/%Y') %></dd>

  <dt>Saída:</dt>
  <dd><%= @item.data_saida.strftime('%d/%m/%Y') %></dd>

</dl>

<%= bootstrap_form_for(@item, method: :delete) do |f| %>
  <%= link_to 'Voltar', reservas_path, class: 'btn btn-primary' %>
  <%= link_to 'Editar', edit_reserva_path(@item), class: 'btn btn-primary' %>

  <%= f.submit 'Remover', class: 'btn btn-danger' %>
<% end %>