config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :clientes
  resources :quartos
  resources :funcionarios
  resources :reservas

  scope :reservas do
    post '/disponibilidade' => 'reservas#disponibilidade', as: :disponibilidade
  end

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  get '/relatorios/dashboard' => 'relatorios#dashboard', as: :dashboard
end

app/models/funcionario.rb
# == Schema Information
#
# Table name: funcionarios
#
#  idfuncionario   :integer          not null, primary key
#  nome            :string(255)      not null
#  email           :string(255)      not null
#  rg              :string(255)      not null
#  cpf             :string(255)      not null
#  telefone        :string(255)
#  celular         :string(255)
#  data_nascimento :date
#  created_at      :datetime
#  updated_at      :datetime
#  deleted_at      :datetime
#

class Funcionario < ActiveRecord::Base
  include ApplicationRecord

  # idfuncionario do usuário administrador.
  ADMIN = 1

  # Campos de busca
  SEARCH_FIELDS = [
    :nome,
    :email
  ]

  # Define o relacionamento (n:m) entre funcionários e reservas.
  has_many :reservas, foreign_key: :idquarto

  # Soft delete: indica para que o registro não seja excluído físicamente
  # do banco de dados, apenas salva a data da remoção e automaticamente
  # não retorna os itens já removidos do sistema
  acts_as_paranoid

  # Adiciona os métodos de validação da senha.
  has_secure_password

  # Valida a obrigatoriedade do nome e do CPF.
  validates :nome, :cpf, presence: true

  # Valida o formato do CPF, a não ser que seja o registro do usuário administrador.
  validates :cpf, cpf: true, unless: :is_admin_user?

  # Valida a unicidade do CPF.
  validates :cpf, uniqueness: true

  # Valida a unicidade do e-mail, se o e-mail estiver cadastrado.
  validates :email, uniqueness: true, if: :email?

  # Antes da validação, define alguns valores para o registro.
  before_validation :set_default_values

  def set_default_values
    # Remove a pontuação do CPF antes de validá-lo.
    self.cpf = self.cpf.gsub(/[^0-9]/, '') if self.cpf.present?

    # Aplica uma criptografia na senha.
    self.password_digest = BCrypt::Password.create(self.cpf)
  end

  # Retorna se o funcionário em questão é o administrador do sistema.
  def is_admin_user?
    id == ADMIN
  end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  # Antes de qualquer ação nesse controller, executa o método "is_admin_user?".
  before_action :is_admin_user?

  # Títulos utilizados nas telas.
  TITLES = {
    index: 'Listagem de funcionários',
    create: 'Novo funcionário',
    show: 'Visualizar funcionário',
    update: 'Editar funcionário',
    destroy: 'Remover funcionário'
  }

  # Verifica se o usuário está logado e se ele é o usuário administrador.
  def is_admin_user?
    unless current_user.is_admin_user?
      flash[:error] = "Você não tem permissão para acessar essa funcionalidade."
      redirect_to root_url
    end
  end

  # Definindo qual é a model usada pela controller.
  def model_klass
    Funcionario
  end

  # Aplicando a ordenação.
  def apply_sorters
    @items = @items.order(:nome)
  end

  # Permite somente parâmetros através de uma "white list".
  def model_params
    params.require(:funcionario).permit(:nome, :email, :rg, :cpf, :telefone, :celular, :data_nascimento)
  end
end

app/views/funcionarios/_form.html.erb
<%= bootstrap_form_for(@item, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-9') do |f| %>
  <%= f.text_field :nome, control_col: 'col-sm-4' %>
  <%= f.email_field :email, control_col: 'col-sm-4' %>
  <%= f.text_field :rg, control_col: 'col-sm-2' %>
  <%= f.text_field :cpf, control_col: 'col-sm-2' %>

  <%= f.text_field :data_nascimento, control_col: 'col-sm-3' %>

  <%= f.text_field :telefone, control_col: 'col-sm-2' %>
  <%= f.text_field :celular, control_col: 'col-sm-2' %>

  <hr />

  <%= f.form_group do %>
    <%= f.primary 'Salvar' %>

    <%= link_to 'Voltar', funcionarios_path, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function () { 
        $("#funcionario_cpf").mask('999.999.999-99');
        $("#funcionario_telefone, #funcionario_celular").mask('(99) 99999-9999');
        $("#funcionario_data_nascimento").mask('00/00/0000');
    });
  </script>
<% end %>

app/views/funcionarios/edit.html.erb
<h3><%= @title %></h3>

<%= render 'form' %>

app/views/funcionarios/index.html.erb
<div class="row page-title">
  <div class="col-xs-8">
    <h2><%= @title %></h2>
  </div>
  <div class="col-xs-4">
    <%= link_to @all_titles[:create], new_funcionario_path, class: 'btn btn-primary pull-right' %>
  </div>
</div>

<h3><%= @url %></h3>

<%= bootstrap_form_tag(url: funcionarios_path, layout: :horizontal, method: :get, html: { class: 'form-search' }) do |f| %>
  <div class="row">
    <label class="col-sm-2 control-label" for="search"><%= I18n.t('general.search') %></label>
    <div class="col-sm-8">
      <%= search_field_tag :search, params[:search], class: 'form-control', hide_label: true, placeholder: I18n.t('general.search_tip', fields: Funcionario.humanize_search_fields.to_sentence.downcase) %>
    </div>
    <div class="col-sm-2">
      <%= f.submit I18n.t('general.search'), class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>E-mail</th>
      <th class="text-center action-column">Ações</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td colspan="4"><%= page_entries_info @items %></td>
    </tr>
  </tfoot>
  <% if @items.present? %>
    <tbody>
      <% @items.each do |funcionario| %>
        <tr>
          <td><%= funcionario.nome %></td>
          <td><%= mail_to funcionario.email %></td>
          <td class="text-center">
            <!-- Single button -->
            <div class="btn-group">
              <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
              </button>
              <ul class="dropdown-menu pull-right">
                <li><a href="<%= funcionario_path(funcionario) %>"><span class="glyphicon glyphicon-eye-open"></span> Ver</a></li>
                <li><a href="<%= edit_funcionario_path(funcionario) %>"><span class="glyphicon glyphicon-edit"></span> Editar</a></li>
                <li role="separator" class="divider"></li>
                <li class="text-danger">
                  <%= bootstrap_form_for(funcionario, method: :delete) do end; %>
                  <a class="btn-delete-funcionario" data-toggle="model" data-target="#modal-funcionario" data-nome="<%= funcionario.nome %>" href="#edit_funcionario_<%= funcionario.id %>">
                    <span class="glyphicon glyphicon-trash"></span> Remover
                  </a>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

<%= paginate(@items) if @items.present? %>

<div class="modal fade" tabindex="-1" role="dialog" id="modal-funcionario">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body">
        Tem certeza que deseja excluir o funcionario <b class="funcionario-nome">nome do funcionario</b>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-danger" data-form="" id="btn-confirm-remove">Remover</button>
      </div>
    </div>
  </div>
</div>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function() {
      $('#modal-funcionario #btn-confirm-remove').click(function() {
        var formId = $(this).data('form');

        if (formId) {
          $(formId).submit();
        }
      });

      $('.btn-delete-funcionario').click(function() {
        var formId = $(this).attr('href'),
          funcionarioNome = $(this).data('nome');

        $('#modal-funcionario .funcionario-nome').html(funcionarioNome);
        $('#modal-funcionario #btn-confirm-remove').data('form', formId);

        $('#modal-funcionario').modal();
      });
    });
  </script>
<% end %>

app/views/funcionarios/new.html.erb
<h3><%= @title %></h3>

<%= render 'form' %>

app/views/funcionarios/show.html.erb
<h3><%= @title %></h3>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @item.nome %></dd>

  <dt>E-mail:</dt>
  <dd><%= @item.email %></dd>

  <dt>RG:</dt>
  <dd><%= @item.rg %></dd>

  <dt>CPF:</dt>
  <dd><%= Util.mask_cpf @item.cpf %></dd>

  <dt>Data de aniversário:</dt>
  <dd><%= l @item.data_nascimento if @item.data_nascimento? %></dd>

  <dt>Telefone:</dt>
  <dd><%= @item.telefone %></dd>

  <dt>Celular:</dt>
  <dd><%= @item.celular %></dd>
</dl>

<%= bootstrap_form_for(@item, method: :delete) do |f| %>
  <%= link_to 'Voltar', funcionarios_path, class: 'btn btn-primary' %>
  <%= link_to 'Editar', edit_funcionario_path(@item), class: 'btn btn-primary' %>

  <%= f.submit 'Remover', class: 'btn btn-danger' %>
<% end %>