config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :clientes
  resources :quartos
  resources :funcionarios
  resources :reservas

  scope :reservas do
    post '/disponibilidade' => 'reservas#disponibilidade', as: :disponibilidade
  end

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  get '/relatorios/dashboard' => 'relatorios#dashboard', as: :dashboard
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Reservas</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= controller_name == 'clientes' ? 'active' : '' %> dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Clientes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= new_cliente_path %>">Novo cliente</a></li>
            <li><a href="<%= clientes_path %>">Listagem de clientes</a></li>
          </ul>
        </li>
        <li class="<%= controller_name == 'quartos' ? 'active' : '' %> dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Quartos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= new_quarto_path %>">Novo quarto</a></li>
            <li><a href="<%= quartos_path %>">Listagem de quartos</a></li>
          </ul>
        </li>
        <li class="<%= controller_name == 'funcionarios' ? 'active' : '' %> dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Funcionários <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= new_funcionario_path %>">Novo funcionario</a></li>
            <li><a href="<%= funcionarios_path %>">Listagem de funcionarios</a></li>
          </ul>
        </li>
        <li class="<%= controller_name == 'reservas' ? 'active' : '' %> dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reservas <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= new_reserva_path %>">Nova reserva</a></li>
            <li><a href="<%= reservas_path %>">Listagem de reservas</a></li>
          </ul>
        </li>
        <li class="<%= controller_name == 'relatorios' ? 'active' : '' %> dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Relatórios <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= dashboard_path %>">Dashboard</a></li>
            <!--<li class="disabled"><a href="javascript:;">Disponilidade</a></li>-->
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="visible-sm-inline"><i class="glyphicon glyphicon-user"></i></span>
            <span class="hidden-sm">Logado como <b><%= @current_user.nome %></b></span>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li class="visible-sm-inline dropdown-header">Logado como <b><%= @current_user.nome %></b></li>
            <li role="separator" class="visible-sm-block divider"></li>
            <li class="text-danger"><a href="<%= logout_url %>"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ['Reservas Hoteleiras', @title].compact.join(' - ') %></title>

    <% version = Faker::Number.number(10) %>

    <link rel="stylesheet" href="/css/base.css?v=<%= version %>" />
    <link rel="stylesheet" href="/css/bootstrap.min.css?v=<%= version %>" />
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css?v=<%= version %>" />
    <link rel="stylesheet" href="/css/font-google-api.css?v=<%= version %>" />

    <%= yield :stylesheets %>

    <%= csrf_meta_tags %>
  </head>
  <body class="<%= @body_css_class || params[:controller] %>">
    <%= render('layouts/menu', format: :html) if @current_user.present? %>

    <div class="container">
      <% if flash.present? %>
        <% proxy_alert_class_hash = { notice: 'info', error: 'danger' } %>
        <div class="alert-container">
          <% flash.each do |name, msg| %>
            <div class="alert alert-<%= proxy_alert_class_hash[name.to_sym].present? ? proxy_alert_class_hash[name.to_sym] : name %> alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
              <%= msg %>
            </div>
          <% end %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <script src="/js/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/jquery.mask.min.js"></script>

    <%= yield :javascripts %>
  </body>
</html>